apiVersion: v1
kind: Namespace
metadata:
  name: ru-deployment
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: discovery-server
  namespace: ru-deployment
  labels:
    name: discovery-server
    service: discovery-server-service
spec:
  replicas: 2
  minReadySeconds: 15
  selector:
    matchLabels:
      name: discovery-server
      type: backend
  template:
    metadata:
      labels:
        name: discovery-server
        type: backend
    spec:
      containers:
      - name: discovery-server
        image: nisumpk/discovery_server
        ports:
        - containerPort: 7001
        env:
        - name: SERVER_PORT
          value: -Dserver.port=7001
        command: ["java"]
        args: ["$(SERVER_PORT)", "-Deureka.instance.preferIpAddress=true", "-jar", "/usr/src/discovery-server-SNAPSHOT.jar"]
        readinessProbe:
          httpGet:
            path: /
          #  host: 127.0.0.1
            port: 7001
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        livenessProbe:
           tcpSocket:
             port: 7001
           initialDelaySeconds: 10
           periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server-service
  namespace: ru-deployment
  labels:
    name: discovery-server-service
spec:
  type: NodePort
  ports:
  - port: 7001
    nodePort: 30050
    targetPort: 7001
    protocol: TCP

  selector:
    name: discovery-server