apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: discovery-server-virtualservice
  namespace: canary
spec:
  hosts:
  - discovery-server
  http:
  - route:
    - destination:
        host: discovery-server
        subset: discovery-server-v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: discovery-server-dr
  namespace: canary
spec:
  host: discovery-server
  subsets:
  - name: discovery-server-v1
    labels:
      version: discovery-server-v1
