apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    name: {{ .Values.application.name  }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP

  selector:
    name: {{ .Values.application.name }}
    deploymentType: {{ .Values.deploymentType }}
